repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: mixed-line-ending
    args: [--fix, lf]
  - id: forbid-submodules
  - id: no-commit-to-branch
    args: [--branch, main]
  - id: check-executables-have-shebangs
  - id: check-symlinks
  - id: check-toml
  - id: check-xml
  - id: check-yaml

- repo: https://gitlab.com/bmares/check-json5
  rev: v1.0.0
  hooks:
  - id: check-json5

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.14
    hooks:
    -   id: ruff-format
    -   id: ruff
        args: [ --fix ]
