version: "latest"

services:
  python-devcontainer: # ! 👈 name of the service
    build: . # path to the Dockerfile
    container_name: python-devcontainer # ! 👈 name of the container
    restart: always # restart the container if it stops
    volumes: # mount the current directory to the container
      - ..:/workspace:cached # mount the current directory as workspace to the container
    environment: # set environment variables
      POETRY_VIRTUALENVS_IN_PROJECT: True
    command: /bin/sh -c "while sleep 1000; do :; done" # * keep the container running